### ISSUE TITLE
Realify the stage submitter

### ISSUE THREAD

**Issue by jdotpz** [mozilla/socorro-infra#238]

**Comment by willkg** [comment]
I missed this issue--sorry about that. I can help out next week.

**Comment by willkg** [comment]
I don't know what's involved here or what it's currently blocked on. @jdotpz added me to the notification list on datadog. I was going to wait until I got a "it's dead, Jim" email and then check out the submitter node to see what it looked like when dead, but it hasn't died since I got on the notification list.

@jdotpz Can you clarify what this issue covers?

**Comment by willkg** [comment]
Moved this to https://bugzilla.mozilla.org/show_bug.cgi?id=1289466

Closing this version out.
