### ISSUE TITLE
Setup socorro-collector separate app in travisland

### ISSUE THREAD

**Issue by jdotpz** [mozilla/socorro-infra#240]

**Comment by willkg** [comment]
I thought we talked about this and decided to set this up in socorroland. Did something change?

I can (probably) go either way, but need to know because it might require additional work to make it run in universes with different gravitational constants.

**Comment by willkg** [comment]
Also, if we're going to set this up in travisland, then I shouldn't spend any time looking at the socorro-infra scripts and building one for setting up the separate collector.

**Comment by willkg** [comment]
Also also, the code is now in https://github.com/mozilla/socorro-collector . I think we should call it Francis so as to differentiate between old collector and new collector.

**Comment by jdotpz** [comment]
We definitely decided that in the meantime, we'd set it up here to facilitate having you access all the things.  However, one bit you didn't hear was after you and I spoke, I was laying out the socorro plans with travis, and he mentioned we have an account setup with those kinds of lax access rules for precisely what you're trying to do, so I'm leaving this todo here to do that when we have time.

**Comment by willkg** [comment]
That's cool. For the record, I'm currently thinking the timeline looks like this:

1. I finish up the socorro-collector work. I've got a bunch of things that *need* to get done and some things that *should* get done and a few things that I want to do because I'm compelled to and I know future me will be cross if I don't.
2. (~ July 5th) After I get most of that done, I'll ping you and we'll work out THE PLAN.
3. (End of July) Then we'll implement THE PLAN.

If THE PLAN requires additional changes, that's cool. We can cross that fiery parasite infested bridge when we get there.

**Comment by willkg** [comment]
I don't think there's any work to be done here, so I'm closing this out.
