### ISSUE TITLE
Setup socorro-collector in our lands, for willkg experimentation etc

### ISSUE THREAD

**Issue by jdotpz** [mozilla/socorro-infra#242]

**Comment by jdotpz** [comment]
@willkg what do you need to move on this, good sir?

**Comment by willkg** [comment]
Right now, nothing.

I need to finish up the code changes. I said I'd look at the script in socorro-infra. When I start doing that, I'll ping you and we can tag-team at that point. I should know a lot more about things then.

**Comment by jdotpz** [comment]
![gday](https://cloud.githubusercontent.com/assets/1373628/16240054/589fe6c2-37ad-11e6-930f-e8943c1c4d8d.gif)
Very good sir, let me know if you want to rally up together on the script.

**Comment by willkg** [comment]
(I sent this in an email last week. Moving the contents here so we can discuss here.)

I've been reading through socorro-infra code so as to figure out how to make the changes we need to make to support the new socorro-collector like we talked about briefly in London. I was thinking something along these lines:

First, the current collector is called "collector" throughout the codebase. You want a new name for the new collector which makes a lot of sense. I originally named the new collector "antenna", but then SHENANIGANS and now it's socorro-collector because SHENANIGANS!. You mentioned naming the new one "gatherer". I think we should go with that.

Second, seems like we need to implement the following:

- terraform/gatherer/* - matches terraform/collector/*
- puppet/modules/socorro/manifests/role/gatherer.pp
- puppet/modules/socorro/files/etc_nginx/conf_d/socorro-gatherer.conf

Then we need to tweak a bunch of files.

Third, then we need a new bin/deploy-socorro.sh . Seems like we'd be copying a lot of it over without any changes, so maybe we move some/most of the functions to a shared file first.

Does that all seem right?

Things I'm not sure about:

1. I make a bunch of changes and ... should I create a pull request? Do you then review it and we work through it until we land it?
2. We have a bunch of changes ... and then what? Are there ways to test the various bits out without hosing the current Socorro?

Also, I've got a tentative 2016q3 goal around getting the new collector in production. Is that ok with you? You're heavily affected by that goal, so maybe you should have a similar or related goal? Then your goal and my goal could go out for Taco Bell periodically.

**Comment by willkg** [comment]
I moved this to https://bugzilla.mozilla.org/show_bug.cgi?id=1289462

Closing this one out.
